FROM ruby:latest

WORKDIR /usr/platform
ADD Gemfile /usr/platform
ADD Gemfile.lock /usr/platform
RUN bundle install

ADD app /usr/platform/app
ADD config/ /usr/platform/config
ADD config.ru /usr/platform
RUN mkdir /usr/platform/builds

EXPOSE 4567

CMD ["puma", "-C", "config/puma.rb"]
