FROM ruby:latest

WORKDIR /usr/platform
ADD Gemfile /usr/platform
ADD Gemfile.lock /usr/platform
RUN bundle install

ADD views/ /usr/platform/views
ADD app.rb /usr/platform
RUN mkdir /usr/platform/uploads
RUN mkdir /usr/platform/builds

EXPOSE 4567
